project:
  type: website

website:
  title: "Acme Semiotics"
  description: "Semiology since 1897"
  favicon: images/favicon.ico
  page-navigation: true
  reader-mode: true
  bread-crumbs: true
  open-graph: true
  navbar:
     logo: images/logo3.png
     left:
       - text: Home
         href: index.qmd
       - about.qmd
     tools:
      - icon: mastodon
        href: https://pkm.social/@bbelton
        rel: me

  sidebar:
    style: "floating"
    collapse-level: 3
    contents:
       - text: "Introduction"
         href: index.qmd
       - text: "Music"
         href: https://karmicresonance.bandcamp.com/music
#         contents:
#         - text: "Karmic Resonance"
#         - href: https://karmicresonance.bandcamp.com
       - section: "Writings"
         contents:
         - posts.qmd
         - text: "Poetry"
           href: "https://acmesemiotics.com/posts.html#category=poetry"
         - section: "Works in Progress"
           contents:
             - text: "The Jewel in the Garden"
               href: "https://quantumjewel.org"


  page-footer: "Copyright 2025"


format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script type="text/javascript"">
          var _paq = window._paq = window._paq || [];
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
          var u="https://acmesemiotics.matomo.cloud/";
          _paq.push(['setTrackerUrl', u+'matomo.php']);
          _paq.push(['setSiteId', '1']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.async=true; g.src='https://cdn.matomo.cloud/acmesemiotics.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
          })();
          </script>

execute:
  freeze: auto
