project:
  type: website

website:
  title: "Acme Semiotics"
  description: "Semiology since 1897"
  favicon: images/favicon.ico
  page-navigation: true
  reader-mode: true
  bread-crumbs: true
  open-graph: true
  navbar:
     logo: images/logo3.png
     left:
       - text: Home
         href: index.qmd
       - about.qmd
     tools:
      - icon: mastodon
        href: https://pkm.social/@bbelton
        rel: me
  sidebar:
    style: "floating"
    collapse-level: 3
    contents:
       - text: "Introduction"
         href: index.qmd
       - text: "Music"
         href: https://karmicresonce.bandcamp.com/music
#         contents:
#         - text: "Karmic Resonance"
#         - href: https://karmicresonance.bandcamp.com
       - section: "Writings"
         contents:
         - posts.qmd
         - text: "Poetry"
           href: "https://acmesemiotics.com/posts.html#category=poetry"
         - section: "Works in Progress"
           contents:
             - text: "The Jewel in the Garden"
               href: "https://quantumjewel.org"

  page-footer: "Copyright 2025"


format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
