project:
  type: website

website:
  site-url: "https://acmesemiotics.com"
  title: "Acme Semiotics"
  description: "Semiology since 1897"
  favicon: images/favicon.ico
  page-navigation: true
  reader-mode: true
  bread-crumbs: true
  open-graph: true
  navbar:
     logo: images/logo3.png
     left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - about.qmd
     tools:
      - icon: mastodon
        href: https://pkm.social/@bbelton
        rel: me
  page-footer: "Copyright 2025"


format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
