---
title: "Introduction"
description: ""
---

thank you miss sobagi for informing that an intro would be fitting and customary.
i will start in the middle.

in debates about whether to use olive oil or butter in cooking a particular dish,
i use both.

in some astrological systems i am a lion, in others i am a sheep. if i could choose
for myself (and why not) i would be a river otter.

floating on my back eating shellfish comes naturally

i don't recall ever having been called a clown; however, my memory is sometimes
faulty.

(i have been called "red-faced monkey"; i am still sorting this out, though i try not to be obsessively attached to it)

sometimes i think there is more to reality than the story that is believed by the most people.

sometimes i don't.

there is One World, but many ways of cooking it

one lives ten days longer for each new thing you try eating; however, i don't know if that is ten days longer than now, or ten days added to some assumed length.

on the subject of airheadedness, my current perspective is that many people suffer from not receiving enough air to their heads.

if i see something not working properly, my tendency is to try to fix it, even if it is none of my business.

sometimes this makes things worse

culinary anthropology is an under-appreciated field of endeavor.

the theory of relativity that is most significant right now is that life is both longer and shorter than i realize

swampwater is good for certain ailments; seawater for others. learning which for what is a useful exercise.

and i will stop in the middle, too. this is not a random matrix, but it is also not complete.