---
title: water
date: 2023-10-10
categories: poetry
---

Already, seas mingle.  
We share water,  
We drink from a common place.  
And go home.  
Yes, you are an ocean.  
You cannot fail.  
Your changing shores Hold the earth in place.  
An atlas.  
But where is the source of oceans?  
  
I open your geography.  
To find a portal to the blue love.  
A swell rises,  
I catch it, float.  
You moan across the way.  
My breath catches  
As soundings resonate.  
Between two deeps -  
But across what space?  
  
My feet are wet, some tide.  
laps at my toes.  
Little birds run to and fro.  
Where my footprints fill with.  
the new sand.  
Stripped bare  
I dive between waves.  
One crashes over my head.  
Between waves  
Between oceans.  
I stand  
On two feet  
The sand is sucked from beneath my toes  
I tilt back.  
And fall head up.  
Tasting salt water  
Stinging my eyes  
I sputter and float  
Face down into a bowl of stars.  
Am I held by oceans resounding  
Or the tension of two surfaces?  
  
Rise, fall  
Underneath, the ocean  
Underneath, the sea.  
Mingling seas,  
I float.  
Resonance and tension,  
I float.  
Between waves.  
I float so easily,  
I float so easily,  
I float so easily.  
Between waves.  
  
We cannot fall.  
We share water.  
We drink from a common place.  
And go home.  
